### ISSUE TITLE
Dashboard bug: IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#105]
If you choose an `end_day` that is larger than the number of days in your simulation (e.g. here:

https://github.com/Urban-Analytics/RAMP-UA/blob/8b5b2e8d51c43192bd1e51028af05708d737b63d/model_parameters/default_dashboard.yml#L6

the dashboard crashes with the error below. I suggest checking that `end_day` does not go behond the number of days in the scenarios.

```
(ramp-ua) Mac-Pro:RAMP-UA nick$ python microsim/dashboard.py 
Traceback (most recent call last):
  File "microsim/dashboard.py", line 1205, in <module>
    create_dashboard()
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/dashboard.py", line 1036, in create_dashboard
    results_tmp = create_counts_dict(conditions_dict,r_range,os.path.join(data_dir,sc_dir[0]),start_day,end_day,start_run,nr_runs,age_cat) # get all
  File "microsim/dashboard.py", line 237, in create_counts_dict
    msoa_count_temp = individuals_tmp[tmp.iloc[:,day] == conditions_dict[key]].groupby(['area']).agg({tmp.columns[day]: ['count']})  
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pandas/core/indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pandas/core/indexing.py", line 2067, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pandas/core/indexing.py", line 703, in _has_valid_tuple
    self._validate_key(k, i)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pandas/core/indexing.py", line 1994, in _validate_key
    self._validate_integer(key, axis)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/pandas/core/indexing.py", line 2063, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by nnelissen** [comment]
end_day and end_run are checked and set to maximum available (across all scenarios) if user specifies a value which is too large
