### ISSUE TITLE
could not find function "local_outbreak"

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#143]
Hi @spoonerf @jabrams23 I'm getting the following error on iteration 7 (running in master branch). Any idea what's causing this?

R[write to console]: Error in local_outbreak(df = df_prob, msoa_infect = msoa_infect, number_people = number_people_local,  : 
  could not find function "local_outbreak"

Traceback (most recent call last):
  File "microsim/microsim_model.py", line 1914, in <module>
    run_script()
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/microsim_model.py", line 1884, in run_script
    m.run(iterations,0)
  File "microsim/microsim_model.py", line 1700, in run
    self.step()
  File "microsim/microsim_model.py", line 1681, in step
    self.calculate_new_disease_status()
  File "microsim/microsim_model.py", line 1554, in calculate_new_disease_status
    self.individuals = self.r_int.calculate_disease_status(self.individuals, self.iteration, self.disease_params)
  File "/Users/nick/research_not_syncd/git_projects/RAMP-UA/microsim/r_interface.py", line 61, in calculate_disease_status
    r_df = self.R.run_status(individuals_reduced, iteration, **disease_params)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 198, in __call__
    .__call__(*args, **kwargs))
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 44, in _
    cdata = function(*args, **kwargs)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/rinterface.py", line 621, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in local_outbreak(df = df_prob, msoa_infect = msoa_infect, number_people = number_people_local,  : 
  could not find function "local_outbreak"

**Comment by spoonerf** [comment]
Hi @nickmalleson can you try again now? It may be that the latest version of the rampuaR package was not being installed, with @jabrams23 local_outbreak function on. I've increased the version which should trigger it to be installed.

**Comment by nickmalleson** [comment]
Thanks I'll try now, give me 20 mins to re-initialise !!

**Comment by jabrams23** [comment]
Hey this is because the local outbreak scenario seems to be on. Make sure to turn this off. The default tilmestep for local outbreak was set to 7 (for no reason) and it is trying to find the local outbreak function which you don’t have cause you don’t have the newest version of the r package.

But the default for local outbreak should be off so maybe I did something wrong in the code

**Comment by spoonerf** [comment]
@jabrams23 Ah yeh it seems to be on and set to 7 in the default.yml

**Comment by nickmalleson** [comment]
Thanks I'll try that now

**Comment by jabrams23** [comment]
ah. Lets make the default off. Sorry for that.

**Comment by nickmalleson** [comment]
It's all good now, thanks both.
