### ISSUE TITLE
people_obesity is not a file in the archive

### ISSUE THREAD

**Issue by spoonerf** [Urban-Analytics/RAMP-UA#163]
Running into an error when I try and run the opencl gui - has anyone else had this issue? 

I've updated to the latest environment.yml and have pulled the latest code.

```
Traceback (most recent call last):
  File "microsim/main.py", line 300, in <module>
    main()
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/main.py", line 194, in main
    opencl_gui, opencl_gpu, use_cache, calibration_params, disease_params)
  File "microsim/main.py", line 211, in run_opencl_model
    snapshot = Snapshot.load_full_snapshot(path=snapshot_cache_filepath)
  File "/Users/fionaspooner/Documents/ECEHH/COVID/RAMP-UA/microsim/opencl/ramp/snapshot.py", line 226, in load_full_snapshot
    buffers = Buffers(**{name: file_data[name] for name in Buffers._fields})
  File "/Users/fionaspooner/Documents/ECEHH/COVID/RAMP-UA/microsim/opencl/ramp/snapshot.py", line 226, in <dictcomp>
    buffers = Buffers(**{name: file_data[name] for name in Buffers._fields})
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/numpy/lib/npyio.py", line 266, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'people_obesity is not a file in the archive'
```

**Comment by spoonerf** [comment]
solved with #162
