### ISSUE TITLE
R/Python model not running

### ISSUE THREAD

**Issue by spoonerf** [Urban-Analytics/RAMP-UA#221]
Running into this issue when trying to run the R/Python model on master branch. Looks like an issue loading packages, but can't figure what is causing it! 

```
R[write to console]: Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: library.dynam(lib, package, package.lib)
  error: shared object ‘magrittr.dylib’ not found

	Error trying to start R: Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: library.dynam(lib, package, package.lib)
  error: shared object ‘magrittr.dylib’ not found
. Libraries probably need installing. Look in the file'R/py_int/covid_run.R' to see which libraries are needed.
Traceback (most recent call last):
  File "microsim/main.py", line 311, in <module>
    main()
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/main.py", line 210, in main
    repetitions, parameters_file)
  File "microsim/main.py", line 255, in run_python_model
    m.run(iterations, 0)
  File "/Users/fionaspooner/Documents/ECEHH/COVID/RAMP-UA/microsim/microsim_model.py", line 120, in run
    self.r_int = RInterface(self.r_script_dir)
  File "/Users/fionaspooner/Documents/ECEHH/COVID/RAMP-UA/microsim/r_interface.py", line 36, in __init__
    raise e
  File "/Users/fionaspooner/Documents/ECEHH/COVID/RAMP-UA/microsim/r_interface.py", line 28, in __init__
    R.initialize_r()
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 198, in __call__
    .__call__(*args, **kwargs))
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 44, in _
    cdata = function(*args, **kwargs)
  File "/Users/fionaspooner/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/rinterface.py", line 621, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: library.dynam(lib, package, package.lib)
  error: shared object ‘magrittr.dylib’ not found

```

**Comment by nickmalleson** [comment]
That's an odd one. Have you tried re-installing things with
```
python setup.py develop
```

**Comment by Sparrow0hawk** [comment]
@spoonerf if you do:

```bash
$ conda activate ramp-ua

(ramp-us) $ R -e "installed.packages()"
```

What output do you get?

**Comment by spoonerf** [comment]
Ah I removed the environment and re-setup everything and it seems to work. I did that yesterday also so not sure what is different now, but either way problem solved! Sorry for the time waste!!
