### ISSUE TITLE
Error in c("rampuaR", ) : argument 2 is empty

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#69]
Hi both,

I'm getting this error, any ideas? I think I'm missing a package, but am not sure which one. I have noticed that the following new packages have been added to `environment.yml`:
  - r-data.table
  - r-mixdist
  - r-mgcv
  - r-RecordLinkage
  - r-tidyselect
and have installed them all without any issues but get the following:

```
R[write to console]: Error in c("rampuaR", ) : argument 2 is empty

	Error trying to start R: Error in c("rampuaR", ) : argument 2 is empty
. Libraries probably need installing. Look in the file'R/py_int/covid_run.R' to see which libraries are needed.
Traceback (most recent call last):
  File "microsim/microsim_model.py", line 1619, in <module>
    run_script()
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/microsim_model.py", line 1595, in run_script
    m.run(iterations)
  File "microsim/microsim_model.py", line 1447, in run
    self.r_int = RInterface(self.r_script_dir)
  File "/Users/nick/research_not_syncd/git_projects/RAMP-UA/microsim/r_interface.py", line 35, in __init__
    raise e
  File "/Users/nick/research_not_syncd/git_projects/RAMP-UA/microsim/r_interface.py", line 27, in __init__
    R.source("covid_run.R")
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 198, in __call__
    .__call__(*args, **kwargs))
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 44, in _
    cdata = function(*args, **kwargs)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/rinterface.py", line 621, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in c("rampuaR", ) : argument 2 is empty
```

**Comment by spoonerf** [comment]
Solved in recent pull request - removed misplaced comma in line 1
