### ISSUE TITLE
Failed to install 'unknown package' from GitHub

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#81]
Sorry that my first message back is about a bug! Any idea what might be causing this? I have pulled the latest of `master` after merging pull request https://github.com/Urban-Analytics/RAMP-UA/pull/76 and have updated my R libraries

```
Saving initial models for analysis ... 
Initialising R interface. Loading R scripts in /Users/nick/gp/RAMP-UA/R/py_int.
R[write to console]: Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref no_ff

  Did you spell the repo owner (`Urban-Analytics`) and repo name (`rampuaR`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

	Error trying to start R: Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref no_ff

  Did you spell the repo owner (`Urban-Analytics`) and repo name (`rampuaR`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
. Libraries probably need installing. Look in the file'R/py_int/covid_run.R' to see which libraries are needed.
Traceback (most recent call last):
  File "microsim/microsim_model.py", line 1619, in <module>
    run_script()
  File "/Users/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/microsim_model.py", line 1595, in run_script
    m.run(iterations)
  File "microsim/microsim_model.py", line 1447, in run
    self.r_int = RInterface(self.r_script_dir)
  File "/Users/nick/gp/RAMP-UA/microsim/r_interface.py", line 35, in __init__
    raise e
  File "/Users/nick/gp/RAMP-UA/microsim/r_interface.py", line 27, in __init__
    R.source("covid_run.R")
  File "/Users/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 198, in __call__
    .__call__(*args, **kwargs))
  File "/Users/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/Users/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 44, in _
    cdata = function(*args, **kwargs)
  File "/Users/nick/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/rpy2/rinterface.py", line 621, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref no_ff

  Did you spell the repo owner (`Urban-Analytics`) and repo name (`rampuaR`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

**Comment by spoonerf** [comment]
Hi Nick, 

Sorry my bad - line 10 on covid_run.R should be:

devtools::install_github("Urban-Analytics/rampuaR", dependencies = F, force = TRUE)

rather than 

devtools::install_github("Urban-Analytics/rampuaR", dependencies = F, force = TRUE, ref = "no_ff")

The latter installs the r package from a branch which no longer exists.

**Comment by nickmalleson** [comment]
Worked :-)
