### ISSUE TITLE
Not reading parameter file (`-npf` argument) causes crash

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#84]
```py
python microsim/microsim_model.py -npf
```
Causes:

```
Not reading a parameters file
Traceback (most recent call last):
  File "microsim/microsim_model.py", line 1619, in <module>
    run_script()
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nick/opt/anaconda3/envs/ramp-ua/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "microsim/microsim_model.py", line 1552, in run_script
    print(f"Running model with the following parameters:\n"
UnboundLocalError: local variable 'calibration_params' referenced before assignment
```

**Comment by nickmalleson** [comment]
Fixed by ignoring calibration parameters when reading from command line (https://github.com/Urban-Analytics/RAMP-UA/commit/08e81d622c9c3681fdd3466609e995b8816c8c8b)
